# Generated by Django 2.1.5 on 2019-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
