# Generated by Django 2.1.5 on 2019-01-29 23:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='herocarrousel',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
