# Generated by Django 2.1.5 on 2019-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_applybanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybanner',
            name='line1',
            field=models.CharField(default='', help_text='Line One', max_length=255),
        ),
        migrations.AddField(
            model_name='applybanner',
            name='line2',
            field=models.CharField(default='', help_text='Line Two', max_length=255),
        ),
        migrations.AddField(
            model_name='applybanner',
            name='useTwolines',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applybanner',
            name='bigtext',
            field=models.CharField(help_text='The Big Text like APPLY NOW', max_length=255),
        ),
    ]
