# Generated by Django 2.1.5 on 2019-01-30 17:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190130_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='herobanner',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('long', 'Long'), ('short', 'Short')], icon='edit')), ('textType', wagtail.core.blocks.ChoiceBlock(choices=[('simple', 'Simple'), ('double', 'double')], icon='edit')), ('text', wagtail.core.blocks.RichTextBlock()), ('text2', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
